<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Data-Driven-FormFill</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>c5a30f61-1982-49bd-8cf7-0becf2e79e63</testSuiteGuid>
   <testCaseLink>
      <guid>dcac9f66-09fd-4e98-b186-25d62268a78e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/FormTest</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>c86bd9d5-eb6a-4d04-a2d4-f820a39c0931</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/formFillDataInternal</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>c86bd9d5-eb6a-4d04-a2d4-f820a39c0931</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>firstName</value>
         <variableId>2737dc07-e223-46a6-8520-2f4379f1f42e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>c86bd9d5-eb6a-4d04-a2d4-f820a39c0931</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>lastName</value>
         <variableId>375b1a98-6142-463f-b43e-4eee647dfa37</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>c86bd9d5-eb6a-4d04-a2d4-f820a39c0931</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>email</value>
         <variableId>3d8bb8ea-b17a-4f63-bce5-eb682c9f1e05</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
